data:
  train:
    type: Polarization_Dataset
    params:
      gt_size: 512
      use_hflip: false
      use_rot: false
      filename_tmpl: "{}"
      stokes_scale: 1.0
      io_backend:
        type: disk
      data_source:
        source1:
          dataroot_gt: ./Datasets/train/dataset_a
        source2:
          dataroot_gt: ./Datasets/train/dataset_b
        source3:
          dataroot_gt: ./Datasets/train/dataset_c
        source4:
          dataroot_gt: ./Datasets/train/dataset_d
